package com.desafio.usuario.exception;

public record ErrorResponse(String error, String message) {
}